namespace rb blublu
namespace cocoa blublu


#photo
struct UserInfo {
    1: i64 userId,
    2: string userName
}

#group
struct GroupInfo {
    1: i64 groupId,
    2: string groupName,
    3: optional i32 unReadInfoNumber,
    4: optional list<UserInfo> groupUsers,

    #最近10条未读信息
    #4: optional list<PhotoObject> unReadInfos,
}

struct PhotoObject {
    1: i64 imageId,
    2: string thumbnilsUrl, #缩略图
    3: string imageUrl, #大图
    4: string title, #标题
    5: i64 uploadDateTime,
    6: optional UserInfo userInfo,
    7: optional double width,
    8: optional double height,
    9: optional GroupInfo groupInfo,
}

struct SearchParam {
    1: optional i32 last_image_id,  # 0 开始, 不设置
    2: optional i32 num,     # 0< pageNum <= 50
    3: optional string order_by,  #newest, (mostloved)
    4: optional i64 groupId, #组id
}


struct GroupSearchParam {
    1: optional string groupName,
    2: optional i64 lastGroupID, #0:  开始
    3: optional string orderBy, #unreads: 未读信息, 
    4: optional string resultColumns,#default: groupId, groupName
}

