include "site_shared.idl"
include "photo_group_head.idl"
namespace rb blublu
namespace cocoa blublu


service photos {
    list<photo_group_head.PhotoObject> getUserPhotos (
        1: string token,    #登陆 token, token 有效期 1天
        2: i64 request_datetime,
        3: string sign,     #签名 , token , seckey
        4: photo_group_head.SearchParam search_param,
    ) throws (1:site_shared.InvalidOperation ouch),

    string test(
        1: string a
    ),

    string addImage(
        1: string token,    #登陆 token, token 有效期 1天
        2: i64 request_datetime,
        3: string sign,     #签名 , token , seckey
        4: string imageString,
        5: i64  groupId, #new add, 0 为无组别
    ) throws (1:site_shared.InvalidOperation ouch),
}
