#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'site_shared_types'
require 'photo_group_head_types'


module Blublu
  class MoniterPlaceInfo
    include ::Thrift::Struct, ::Thrift::Struct_Union
    ID = 1
    NAME = 2
    PHOTONUM = 3

    FIELDS = {
      ID => {:type => ::Thrift::Types::I64, :name => 'id'},
      NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
      PHOTONUM => {:type => ::Thrift::Types::I32, :name => 'photoNum'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class MoniterImage
    include ::Thrift::Struct, ::Thrift::Struct_Union
    IMAGE_ID = 1
    PLACE_ID = 2
    IMAGE_URL = 3
    DATE_TIME = 4

    FIELDS = {
      IMAGE_ID => {:type => ::Thrift::Types::I64, :name => 'image_id'},
      PLACE_ID => {:type => ::Thrift::Types::I64, :name => 'place_id'},
      IMAGE_URL => {:type => ::Thrift::Types::STRING, :name => 'image_url'},
      DATE_TIME => {:type => ::Thrift::Types::I64, :name => 'date_time'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end
