#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'site_shared_types'


module Blublu
  class UserInfo
    include ::Thrift::Struct, ::Thrift::Struct_Union
    USERID = 1
    USERNAME = 2

    FIELDS = {
      USERID => {:type => ::Thrift::Types::I64, :name => 'userId'},
      USERNAME => {:type => ::Thrift::Types::STRING, :name => 'userName'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class PhotoObject
    include ::Thrift::Struct, ::Thrift::Struct_Union
    IMAGEID = 1
    THUMBNILSURL = 2
    IMAGEURL = 3
    TITLE = 4
    UPLOADDATETIME = 5
    USERINFO = 6
    WIDTH = 7
    HEIGHT = 8

    FIELDS = {
      IMAGEID => {:type => ::Thrift::Types::I64, :name => 'imageId'},
      THUMBNILSURL => {:type => ::Thrift::Types::STRING, :name => 'thumbnilsUrl'},
      IMAGEURL => {:type => ::Thrift::Types::STRING, :name => 'imageUrl'},
      TITLE => {:type => ::Thrift::Types::STRING, :name => 'title'},
      UPLOADDATETIME => {:type => ::Thrift::Types::I64, :name => 'uploadDateTime'},
      USERINFO => {:type => ::Thrift::Types::STRUCT, :name => 'userInfo', :class => ::Blublu::UserInfo, :optional => true},
      WIDTH => {:type => ::Thrift::Types::DOUBLE, :name => 'width', :optional => true},
      HEIGHT => {:type => ::Thrift::Types::DOUBLE, :name => 'height', :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class SearchParam
    include ::Thrift::Struct, ::Thrift::Struct_Union
    LAST_IMAGE_ID = 1
    NUM = 2
    ORDER_BY = 3

    FIELDS = {
      LAST_IMAGE_ID => {:type => ::Thrift::Types::I32, :name => 'last_image_id', :optional => true},
      NUM => {:type => ::Thrift::Types::I32, :name => 'num', :optional => true},
      ORDER_BY => {:type => ::Thrift::Types::STRING, :name => 'order_by', :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end
