#
# Autogenerated by Thrift Compiler (0.8.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#


module Blublu
    class InvalidOperation < ::Thrift::Exception
      include ::Thrift::Struct, ::Thrift::Struct_Union
      WHAT = 1
      WHY = 2

      FIELDS = {
        WHAT => {:type => ::Thrift::Types::I32, :name => 'what'},
        WHY => {:type => ::Thrift::Types::STRING, :name => 'why'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

  end
