#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'system_types'

module Blublu
  module System
    class Client
      include ::Thrift::Client

      def getUpdate(token, request_datetime, sign, nowVersion, system, channel)
        send_getUpdate(token, request_datetime, sign, nowVersion, system, channel)
        return recv_getUpdate()
      end

      def send_getUpdate(token, request_datetime, sign, nowVersion, system, channel)
        send_message('getUpdate', GetUpdate_args, :token => token, :request_datetime => request_datetime, :sign => sign, :nowVersion => nowVersion, :system => system, :channel => channel)
      end

      def recv_getUpdate()
        result = receive_message(GetUpdate_result)
        return result.success unless result.success.nil?
        raise result.ouch unless result.ouch.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'getUpdate failed: unknown result')
      end

    end

    class Processor
      include ::Thrift::Processor

      def process_getUpdate(seqid, iprot, oprot)
        args = read_args(iprot, GetUpdate_args)
        result = GetUpdate_result.new()
        begin
          result.success = @handler.getUpdate(args.token, args.request_datetime, args.sign, args.nowVersion, args.system, args.channel)
        rescue ::Blublu::InvalidOperation => ouch
          result.ouch = ouch
        end
        write_result(result, oprot, 'getUpdate', seqid)
      end

    end

    # HELPER FUNCTIONS AND STRUCTURES

    class GetUpdate_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      TOKEN = 1
      REQUEST_DATETIME = 2
      SIGN = 3
      NOWVERSION = 4
      SYSTEM = 5
      CHANNEL = 6

      FIELDS = {
        TOKEN => {:type => ::Thrift::Types::STRING, :name => 'token'},
        REQUEST_DATETIME => {:type => ::Thrift::Types::I64, :name => 'request_datetime'},
        SIGN => {:type => ::Thrift::Types::STRING, :name => 'sign'},
        NOWVERSION => {:type => ::Thrift::Types::STRING, :name => 'nowVersion'},
        SYSTEM => {:type => ::Thrift::Types::STRING, :name => 'system'},
        CHANNEL => {:type => ::Thrift::Types::STRING, :name => 'channel'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class GetUpdate_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0
      OUCH = 1

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::STRUCT, :name => 'success', :class => ::Blublu::UpdateInfo},
        OUCH => {:type => ::Thrift::Types::STRUCT, :name => 'ouch', :class => ::Blublu::InvalidOperation}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

  end

end
