#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'site_shared_types'


module Blublu
  class UpdateInfo
    include ::Thrift::Struct, ::Thrift::Struct_Union
    VERSION = 1
    UPDATEMSG = 2
    FORCEUPDATE = 3
    DOWNLOADURL = 4

    FIELDS = {
      VERSION => {:type => ::Thrift::Types::STRING, :name => 'version'},
      UPDATEMSG => {:type => ::Thrift::Types::STRING, :name => 'updateMsg'},
      FORCEUPDATE => {:type => ::Thrift::Types::BOOL, :name => 'forceUpdate'},
      DOWNLOADURL => {:type => ::Thrift::Types::STRING, :name => 'downloadUrl', :optional => true}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end
