#
# Autogenerated by Thrift Compiler (0.9.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'user_types'

module Blublu
  module User
    class Client
      include ::Thrift::Client

      def login(request_datetime, sign, email, password)
        send_login(request_datetime, sign, email, password)
        return recv_login()
      end

      def send_login(request_datetime, sign, email, password)
        send_message('login', Login_args, :request_datetime => request_datetime, :sign => sign, :email => email, :password => password)
      end

      def recv_login()
        result = receive_message(Login_result)
        return result.success unless result.success.nil?
        raise ::Thrift::ApplicationException.new(::Thrift::ApplicationException::MISSING_RESULT, 'login failed: unknown result')
      end

    end

    class Processor
      include ::Thrift::Processor

      def process_login(seqid, iprot, oprot)
        args = read_args(iprot, Login_args)
        result = Login_result.new()
        result.success = @handler.login(args.request_datetime, args.sign, args.email, args.password)
        write_result(result, oprot, 'login', seqid)
      end

    end

    # HELPER FUNCTIONS AND STRUCTURES

    class Login_args
      include ::Thrift::Struct, ::Thrift::Struct_Union
      REQUEST_DATETIME = 1
      SIGN = 2
      EMAIL = 3
      PASSWORD = 4

      FIELDS = {
        REQUEST_DATETIME => {:type => ::Thrift::Types::I64, :name => 'request_datetime'},
        SIGN => {:type => ::Thrift::Types::STRING, :name => 'sign'},
        EMAIL => {:type => ::Thrift::Types::STRING, :name => 'email'},
        PASSWORD => {:type => ::Thrift::Types::STRING, :name => 'password'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

    class Login_result
      include ::Thrift::Struct, ::Thrift::Struct_Union
      SUCCESS = 0

      FIELDS = {
        SUCCESS => {:type => ::Thrift::Types::I32, :name => 'success'}
      }

      def struct_fields; FIELDS; end

      def validate
      end

      ::Thrift::Struct.generate_accessors self
    end

  end

end
